-- Schema definition for vendors in archive layer
-- Generated by Data Architect

CREATE TABLE IF NOT EXISTS archive.arch_vendors (
    vendors_id BIGINT PRIMARY KEY,
    -- Core Fields
    name VARCHAR(255),
    description TEXT,
    status VARCHAR(50),
    type VARCHAR(50),
    
    -- Metrics
    amount DECIMAL(19, 4),
    quantity INT,
    score DOUBLE PRECISION,
    
    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source_system VARCHAR(100),
    ingestion_batch_id UUID,
    
    -- Archive Specific
    archived_at TIMESTAMP
);

-- Indices
CREATE INDEX idx_arch_vendors_status ON archive.arch_vendors(status);
CREATE INDEX idx_arch_vendors_created ON archive.arch_vendors(created_at);
