-- Schema definition for devices in staging layer
-- Generated by Data Architect

CREATE TABLE IF NOT EXISTS staging.stg_devices (
    devices_id BIGINT PRIMARY KEY,
    -- Core Fields
    name VARCHAR(255),
    description TEXT,
    status VARCHAR(50),
    type VARCHAR(50),
    
    -- Metrics
    amount DECIMAL(19, 4),
    quantity INT,
    score DOUBLE PRECISION,
    
    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source_system VARCHAR(100),
    ingestion_batch_id UUID,
    
    -- Staging Specific
    raw_payload JSONB
);

-- Indices
CREATE INDEX idx_stg_devices_status ON staging.stg_devices(status);
CREATE INDEX idx_stg_devices_created ON staging.stg_devices(created_at);
